### ISSUE TITLE
ConnectorSymbol.getTargetPort() returns wrong Port

### ISSUE THREAD

**Issue by ManuelSchrick** [EmbeddedMontiArc/EmbeddedMontiArc#22]
In some cases (unfortunately I couldn't find out which ones) the getTargetPort() Method of ConnectorSymbol class returns a wrong Port. I've implemented a test on the branch "bug/connector-returns-wrong-port" that fails. In there I use the FAS-Model and check if the ports returned in getSourcePort() and getTargetPort() have different full names, which should be the case for all connectors in that model.

UPDATE:
I figured out that, if one changes the port for which the test is failing to be a non-array-port, the test will pass. However a simpler model with array ports of the same name will work just fine...

**Comment by ManuelSchrick** [comment]
@vonwenckstern Kannst du das bitte jemandem zuweisen? Ich weiß nicht genau, wer dafür zuständig ist...

**Comment by vonwenckstern** [comment]
@ManuelSchrick @sschneiders had a lot to do the last weeks; that's why he will look at if he has some time.

**Comment by sschneiders** [comment]
I updated your branch and added additional information to the error messages.
The method works correctly, however the model has errors.

For example:

The given connector was:
```
connect LeverUp_stat -> tempo.LeverUp_stat;
```

But, the port in Tempomat is called 
```
LeverUp_Stat
```

I fixed this and a few other issues.

However, the model is still wrong, but the error messages should be more helpful now.
