### ISSUE TITLE
Remove Kotlin code from Project

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/EmbeddedMontiArc#5]
Hi,
the main MontiCore languages are only written in Java, so that everybody at the SE chair can use them.
Please do not insert Kotlin code!

Please write the functionality you use in Java.
The Kotlin code can also not be analyzed with code climate.
*Only* use Kotlin code in your 2Kotlin project, nowhere else.

Thank you

**Comment by progaddict** [comment]
yes, sure, I'll do it.
